### ISSUE TITLE
Please update this package

### ISSUE THREAD

**Issue by u0x01** [iris-contrib/sessiondb#2]
build error with new version iris:
    ../../github.com/iris-contrib/sessiondb/redis/database.go:40: undefined: utils.DeserializeBytes
    ../../github.com/iris-contrib/sessiondb/redis/database.go:49: undefined: utils.SerializeBytes

**Comment by kataras** [comment]
Hmm I think docs and examples points to the `github.com/kataras/go-sessions/sessiondb/redis` I will update it for any case too, thanks
